[book]

[build]
extra-watch-dirs = ["../mdbook-xref/src/", "../mdbook-figure/src/", "../mdbook-abbr2/src"]

[preprocessor.xref]
command = "cargo run -p mdbook-xref"

[preprocessor.figure]
before = ["xref"]
command = "cargo run -p mdbook-figure"

[preprocessor.abbr2]
before = ["xref"]
command = "cargo run -p mdbook-abbr2"
path = "abbreviations.csv"
separator = true

[output.html]
additional-css = ["style.css"]